---
server:
  port: 8181
spring:
  security:
    oauth2:
      client:
        registration:
          auth-client:
            authorization-grant-type: "client_credentials"
            client-id: "auth-client"
            client-secret: "secret"
            scope: "internal"
            client-name: "auth-client"
        provider:
          auth-client:
            token-uri: "http://192.168.100.18:8181"
clients:
- clientId: "auth-client"
  clientSecret: "auth-secret"
  authorizationGrantTypes:
  - "client_credentials"
  scopes:
  - "internal"
  - "authenticate"
  accessTokenExpired: 30000
  refreshTokenExpired: 1234000
  redirectUrl: "null"
- clientId: "msrfyl-client"
  clientSecret: "msrfyl-secret"
  authorizationGrantTypes:
  - "authorization_code"
  - "refresh_token"
  scopes:
  - "user.manage"
  - "user.read"
  accessTokenExpired: 30000
  refreshTokenExpired: 1234000
  redirectUrl: "https://oauth.pstmn.io/v1/callback"
